CREATE OR REPLACE DATABASE "Vunerability Assessment"; 

CREATE OR REPLACE SCHEMA RAW;
DROP SCHEMA RAW;

USE SCHEMA PUBLIC;


----------Add
CREATE OR REPLACE VIEW LSOA_BOUNDARIES AS SELECT * FROM ONS.CURATED."lSOA Boundaries 2021";

CREATE OR REPLACE VIEW UK_HOUSEHOLDS AS SELECT * FROM UK_HOUSEHOLDS.ARK_MARKETPLACE.UK_HOUSEHOLDS;

CREATE OR REPLACE VIEW UK_POSTCODES AS SELECT * FROM OS.CURATED."UK Postcodes with Points";

CREATE OR REPLACE VIEW LSOA_DOMESTIC_GAS AS SELECT * FROM ONS.CURATED."LSOA Domestic Gas 2010 to 2021";

CREATE OR REPLACE VIEW LSOA_DOMESTIC_ELECTRICITY AS SELECT * FROM ONS.CURATED."LSOA Domestic Electricity 2010 - 21";

CREATE OR REPLACE VIEW "OA2011 to OA2021 Lookup" AS SELECT * FROM ONS.CURATED."OA2011 to OA2021 Lookup";

CREATE OR REPLACE VIEW "LSOA2011 to LOSA2021 Lookup" as SELECT * FROM ONS.CURATED."LSOA 2011 to LSOA 2021 Lookup Table";

create or replace view "OA Boundaries 2021" as select * from ONS.CURATED."OA Boundaries 2021";